baseURL = 'http://www.example.com/'
languageCode = 'en-us'
title = 'Yannis Rizos'
theme = 'template'

[params]
  recentPostsLimit = 6

[params.social]
linkedin = 'https://www.linkedin.com/in/yrizos/'
github = 'https://github.com/yrizos'
medium = 'https://medium.com/@yrizos'
goodreads = 'https://www.goodreads.com/user/show/68793210-yannis-rizos'

